kind: Service
apiVersion: v1
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: mongodb-food-fusion-service
spec:
  selector:
    app: mongodb-food-fusion-deployment
  ports:
    - port: 27017
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: pgadmin
spec:
  selector:
    app: pgadmin
  ports:
    - port: 80
      nodePort: 30200
  type: NodePort