apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-order-service
data:
  POSTGRES_DB: aws_ssm_db_name
  POSTGRES_HOST: aws_ssm_db_host
  MONGO_INITDB_DATABASE: "root"
  MONGO_INITDB_HOST: aws_ssm_documentdb_host